apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        pip install --upgrade pip
        pip install -r requirements.txt
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

